#+TITLE: Cross cluster vm migration demo
#+DATE: <2026-03-16 Mon>


This guide will capture the flow I used to set up an environment that demonstrates how to live migrate a virtual machine between two OpenShift clusters. The aim of this document is to make it trivial for me to recreate the same demonstration in future.


* Pre-requisites

** Kubernetes tools

This guide assumes you have the ~oc~ OpenShift Client already installed locally. If you don't have this already it is available via brew:

#+NAME: Install openshift client
#+begin_src bash
brew install openshift-client
#+end_src


** Base infrastructure

This guide assumes you already have an OpenShift cluster and Red Hat Advanced Cluster Management in place. For my purposes I used the standard [[https://catalog.demo.redhat.com/services/user-jablair-redhat-com/published.ocp4-acm-demo.prod-lbjhr][RHACM demo base environment]].

Before we begin, let's ensure we are logged into the hub cluster with ~oc~:

#+NAME: Login to openshift hub cluster
#+begin_src bash
source .env
oc login "${HUB_API_URL}" --username "${HUB_USERNAME}" --password "${HUB_PASSWORD}" --insecure-skip-tls-verify
#+end_src

#+RESULTS: Login to openshift hub cluster
#+begin_example
WARNING: Using insecure TLS client config. Setting this option is not supported!

Login successful.

You have access to 90 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "default".
Welcome! See 'oc help' to get started.
#+end_example


We also want to give our hub kube context a specific name so we can refer to it programatically moving forward:

#+NAME: Set hub context name
#+begin_src bash
oc config rename-context $(oc config current-context) hub
#+end_src

#+RESULTS: Set hub context name
#+begin_example
Context "default/api-cluster-m4nxh-dynamic-redhatworkshops-io:6443/admin" renamed to "hub".
#+end_example


* Configuring the hub cluster

** Adding managed clusters

For our demonstration we are going to connect two workload clusters to our acm hub. The workload clusters will run our virtual machines and we'll migrate machines between the two workload clusters.


* Configure edge one cluster

** Create kube context

We'll refer to our edge one cluster with a specific kube context below, so let's login to it now and create that.

#+NAME: Login to openshift edge one cluster
#+begin_src bash
source .env
oc login "${EDGE1_API_URL}" --username "${EDGE1_USERNAME}" --password "${EDGE1_PASSWORD}" --insecure-skip-tls-verify
#+end_src

#+RESULTS: Login to openshift edge one cluster
#+begin_example
WARNING: Using insecure TLS client config. Setting this option is not supported!

Login successful.

You have access to 79 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "default".
#+end_example

#+NAME: Set edge one context name
#+begin_src bash
oc config rename-context $(oc config current-context) edge1
#+end_src

#+RESULTS: Set edge one context name
#+begin_example
Context "default/api-cluster-xf2wm-dynamic-redhatworkshops-io:6443/admin" renamed to "edge1".
#+end_example


** Install virt operator

Our edge one cluster is not currently running OpenShift Virtualization, we need to enable that by installing the operator, we can do that by creating a ~Subscription~

#+NAME: Create edge one virt subscription
#+begin_src bash
oc --context edge1 apply --filename manifests/virt-operator.yaml
#+end_src

#+RESULTS: Create edge one virt subscription
#+begin_example
namespace/openshift-cnv created
subscription.operators.coreos.com/kubevirt-hyperconverged created
operatorgroup.operators.coreos.com/openshift-cnv created
#+end_example


** Create hyperconverged resource

Once the operator is installed we can create the mandatory ~hyperconverged~ custom resource definition to enable virtualization.  Note we are specifically enabling the new ~decentralizedLiveMigration~ feature gate which will enable us to use cross cluster live migration.

#+NAME: Create edge one hyperconverged resource
#+begin_src bash
oc --context edge1 apply --filename manifests/hyperconverged.yaml
#+end_src

#+RESULTS: Create edge one hyperconverged resource
#+begin_example
hyperconverged.hco.kubevirt.io/kubevirt-hyperconverged created
#+end_example


** Install migration operator

Given we're wanting to demonstrate migrating virtual machines across clusters we also need to install the Migration Toolkit for Virtualization operator. As with the virt operator we can do this by creating a ~Subscription~.

#+NAME: Create edge one mtv subscription
#+begin_src bash
oc --context edge1 apply --filename manifests/mtv-operator.yaml
#+end_src

#+RESULTS: Create edge one mtv subscription
#+begin_example
namespace/openshift-mtv created
subscription.operators.coreos.com/mtv-operator created
operatorgroup.operators.coreos.com/openshift-mtv created
#+end_example


** Create forklift controller resource

Once the mtv operator is installed we can create the required ~forkliftcontroller~ resource. Note we are specifically enabling the new ~feature_ocp_live_migration~ feature flag that will enable us to use cross cluster live migration.

#+NAME: Create edge one forkliftcontroller resource
#+begin_src bash
oc --context edge1 apply --filename manifests/forklift-controller.yaml
#+end_src

#+RESULTS: Create edge one forkliftcontroller resource
#+begin_example
forkliftcontroller.forklift.konveyor.io/forklift-controller created
#+end_example


* Configure edge two cluster

** Create kube context

We'll refer to our edge two cluster with a specific kube context below, so let's login to it now and create that.

#+NAME: Login to openshift edge two cluster
#+begin_src bash
source .env
oc login "${EDGE2_API_URL}" --username "${EDGE2_USERNAME}" --password "${EDGE2_PASSWORD}" --insecure-skip-tls-verify
#+end_src

#+RESULTS: Login to openshift edge two cluster
#+begin_example
WARNING: Using insecure TLS client config. Setting this option is not supported!

Login successful.

You have access to 79 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "default".
#+end_example

#+NAME: Set edge two context name
#+begin_src bash
oc config rename-context $(oc config current-context) edge2
#+end_src

#+RESULTS: Set edge two context name
#+begin_example
Context "default/api-cluster-dxvdf-dynamic-redhatworkshops-io:6443/admin" renamed to "edge2".
#+end_example


** Install virt operator

Our edge two cluster is not currently running OpenShift Virtualization, we need to enable that by installing the operator, we can do that by creating a ~Subscription~

#+NAME: Create edge two virt subscription
#+begin_src bash
oc --context edge2 apply --filename manifests/virt-operator.yaml
#+end_src

#+RESULTS: Create edge two virt subscription
#+begin_example
namespace/openshift-cnv created
subscription.operators.coreos.com/kubevirt-hyperconverged created
operatorgroup.operators.coreos.com/openshift-cnv created
#+end_example


** Create hyperconverged resource

Once the operator is installed we can create the mandatory ~hyperconverged~ custom resource definition to enable virtualization.  Note we are specifically enabling the new ~decentralizedLiveMigration~ feature gate which will enable us to use cross cluster live migration.

#+NAME: Create edge two hyperconverged resource
#+begin_src bash
oc --context edge2 apply --filename manifests/hyperconverged.yaml
#+end_src

#+RESULTS: Create edge two hyperconverged resource
#+begin_example
hyperconverged.hco.kubevirt.io/kubevirt-hyperconverged created
#+end_example


** Install migration operator

Given we're wanting to demonstrate migrating virtual machines across clusters we also need to install the Migration Toolkit for Virtualization operator. As with the virt operator we can do this by creating a ~Subscription~.

#+NAME: Create edge two mtv subscription
#+begin_src bash
oc --context edge2 apply --filename manifests/mtv-operator.yaml
#+end_src

#+RESULTS: Create edge two mtv subscription
#+begin_example
namespace/openshift-mtv created
subscription.operators.coreos.com/mtv-operator created
operatorgroup.operators.coreos.com/openshift-mtv created
#+end_example


** Create forklift controller resource

Once the mtv operator is installed we can create the required ~forkliftcontroller~ resource. Note we are specifically enabling the new ~feature_ocp_live_migration~ feature flag that will enable us to use cross cluster live migration.

#+NAME: Create edge two forkliftcontroller resource
#+begin_src bash
oc --context edge2 apply --filename manifests/forklift-controller.yaml
#+end_src

#+RESULTS: Create edge two forkliftcontroller resource
#+begin_example
forkliftcontroller.forklift.konveyor.io/forklift-controller created
#+end_example


* Create vm migration demo

With the base cluster infrastructure now in place we can create the virtual machine and migration providers to enable us to move it around.

** Create edge one migration provider

Once the mtv operator is running we can create the ~secret~ and ~provider~ that will tell the migration toolkit on our edge one cluster how to talk to openshift virtualization on our edge two cluster.

#+begin_quote:
Note: Given this is a short lived demonstration environment to keep life simple we will disable certificate validation and simply use our kube context token as the auth token for the provider. Obviously this is not the approach you should use in production!
#+end_quote

#+NAME: Create edge one cluster provider
#+begin_src bash
export HUB_TOKEN=$(oc --context edge2 whoami --show-token)
envsubst < manifests/edge2-provider.yaml | oc --context edge1 apply --filename -
#+end_src

#+RESULTS: Create edge one cluster provider
#+begin_example
secret/edge-two-cluster created
provider.forklift.konveyor.io/edge-two-cluster created
#+end_example

#+RESULTS: Create hub cluster provider
#+begin_example
secret/hub-cluster created
provider.forklift.konveyor.io/hub-cluster created
#+end_example


* Create demo virtual machine

We now need to create the virtual machine we'll use to demonstrate cross cluster migration. Given this migration will be cross aws region traffic we'll keep this as lightweight as possible.

#+NAME: Create virtual machine
#+begin_src bash
oc --context hub apply --filename manifests/virtual-machine.yaml
#+end_src

#+RESULTS: Create virtual machine
#+begin_example
namespace/vm-test created
virtualmachine.kubevirt.io/fedora-vm created
#+end_example
