#+TITLE: Zero Trust Workload Identity Manager Demo
#+DATE: <2026-04-03 Fri>


A short demo setup for the Zero Trust Workload Identity Manager in OpenShift.


* Pre-requisites

- [ ] An OpenShift Cluster with cluster admin permissions, these instructions have been tested with OpenShift ~4.21~.

- [ ] The ~oc~ command line tool available in your path. Before we begin, let's ensure we are logged into the hub cluster with ~oc~:

#+NAME: Login to openshift cluster
#+begin_src bash
source .env
oc login "${OCP_API_URL}" --username "${OCP_USERNAME}" --password "${OCP_PASSWORD}" --insecure-skip-tls-verify
#+end_src

#+RESULTS: Login to openshift cluster
#+begin_example
WARNING: Using insecure TLS client config. Setting this option is not supported!

Login successful.

You have access to 79 projects, the list has been suppressed. You can list all projects with 'oc projects'

Using project "default".
#+end_example


* Install ztwim operator

The Zero Trust Workload Identity Manager is an Openshift Day-2 Operator designed to automate the setup and management of SPIFFE/SPIRE components. We'll install that now by creating a ~Subscription~ resource.

#+NAME: Install ztwim operator
#+begin_src bash
oc apply --filename manifests/operator.yaml
#+end_src


* Create ztwim crd

Once the operator is installed we can create an instance of the ~ZeroTrustWorkloadIdentityManager~ meta resource followed by each of the required sub components.

As outlined in the [[https://docs.redhat.com/en/documentation/openshift_container_platform/4.21/html/security_and_compliance/zero-trust-workload-identity-manager#zero-trust-manager-configuration][documentation]] we must deploy the operands in the following sequence to ensure successful installation:
  - ZeroTrustWorkloadIdentityManager CR
  - SPIRE Server
  - SPIRE Agent
  - SPIFFE CSI driver
  - SPIRE OIDC discovery provider

#+NAME: Create ztwim resouce
#+begin_src bash
oc apply --filename manifests/ztwim.yaml
#+end_src

#+RESULTS: Create ztwim resouce
#+begin_example
zerotrustworkloadidentitymanager.operator.openshift.io/cluster created
#+end_example

#+NAME: Create spire server resource
#+begin_src bash
oc apply --filename manifests/spireserver.yaml
#+end_src

#+RESULTS: Create spire server resource
#+begin_example
spireserver.operator.openshift.io/cluster created
#+end_example
